# Generated by Django 3.1.4 on 2021-01-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210117_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='dateC',
        ),
    ]
