# Generated by Django 3.1.4 on 2021-01-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210117_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dateC',
            new_name='date',
        ),
    ]
